INPUT:
  TYPE: "DEPTH"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
#  WEIGHT: "/home/yuxiang/Projects/unseen_clustering/data/checkpoints/MaskRCNN_Depth_TODv5.pth"
#  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STEM_IN_CHANNELS: 3
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 3
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("tabletop_object_dataset_depth", )
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 4
  VISUALIZE: False
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 16
  STEPS: (480000, 640000)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 12500
  START_ITER: 0
OUTPUT_DIR: output/tabletop/Depth_no_pretrain_train_4/
